services:
  - type: web
    name: bot-paxg-patterns
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_paxg.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ACCOUNT_SIZE
        value: "200"
      - key: STOP_MODE
        value: half
      - key: PYTHON_VERSION
        value: "3.11.0"
